CREATE TABLE STUDENT(
	ID VARCHAR(300),
	NAME VARCHAR(20),
	MAJOR VARCHAR(20),
	GENDER CHAR(1) CHECK(GENDER IN ('M','W')),
	BIRTH DATE CHECK(BIRTH >= '1980-01-01'),
	CONSTRAINT PRIMARY KEY(ID)
);

INSERT INTO STUDENT
(ID, NAME, MAJOR, GENDER, BIRTH)
VALUES(2022001, '정다솔', '기계공학', 'M', '2000-12-13');

INSERT INTO STUDENT
(ID, NAME, MAJOR, GENDER, BIRTH)
VALUES(2022002, '김사과', '기계공학', 'W', '2003-06-23');

--영화정보
--	배우
--	장르
--	제목
--	감독
--	개봉날짜
--	19
CREATE TABLE MOVIE(
	ACTOR VARCHAR(500),
	GENRE VARCHAR(20),
	TITLE VARCHAR(100),
	DIRECTOR VARCHAR(20),
	MOVIEDATE DATE CONSTRAINT M_DATE CHECK(MOVIEDATE >= '1900-01-01'),
	AGE CHAR(2) CONSTRAINT M_AGE CHECK(AGE IN ('AA','19'))
);


-- FOREIGN KEY 설정하는 방법

CREATE TABLE TEST1(
	A VARCHAR(20) PRIMARY KEY,
	B VARCHAR(20),
	C VARCHAR(20),
	D VARCHAR(20)
);

CREATE TABLE TEST2(
	E VARCHAR(20) PRIMARY KEY,
	F VARCHAR(20),
	A VARCHAR(20),
	CONSTRAINT TEST2_FK FOREIGN KEY(A)
		REFERENCES TEST1(A)
);
INSERT INTO TEST1 VALUES('a','b','c','d');
INSERT INTO TEST2 VALUES('e','f','a');

CREATE TABLE TEST3(
	G VARCHAR(20) NOT NULL,
	H VARCHAR(20) UNIQUE
);



