#한줄 주석
/*
여러줄
주석
 */
#데이터베이스 생성
CREATE DATABASE TESTWORLD;
#데이터베이스 사용
USE TESTWORLD;
#테이블 생성
CREATE TABLE TEST(
	INTDATA INT,
	STRDATA VARCHAR(300)
);

#아래와 같은 형태로 PK를 주면 그 제약조건의 이름은
#시스템이 지어서 만들어준다.(우리가 관리하기 힘들다)
#제약조건 명 확인
#select * from information_schema.table_Constraints where table_name = '테이블명';
select * from information_schema.table_Constraints
where table_name = 'CAR';
CREATE TABLE CAR(
	CARNUM VARCHAR(300),
	BRAND VARCHAR(300),
	COLOR VARCHAR(300),
	PRICE INT
);

#아래 방법을 더 많이 쓰게 된다.
CREATE TABLE CAR(
	CARNUM VARCHAR(300),
	BRAND VARCHAR(300),
	COLOR VARCHAR(300),
	PRICE INT,
	CONSTRAINT CAR_PK PRIMARY KEY(CARNUM)
);

#테이블 삭제
DROP TABLE CAR;

#테이블 수정

#컬럼추가
ALTER TABLE CAR ADD COLUMN OWNER VARCHAR(300);
#컬럼 수정(타입)
ALTER TABLE CAR MODIFY COLUMN OWNER VARCHAR(301);
#컬럼 수정(이름+타입)
ALTER TABLE CAR CHANGE COLUMN OWNER OWNER2 VARCHAR(300);

#제약조건 추가
ALTER TABLE CAR ADD CONSTRAINT CAR_PK PRIMARY KEY(CARNUM);
#제약조건 삭제
ALTER TABLE CAR DROP CONSTRAINT CAR_PK;


#FK 부여하기
CREATE TABLE OWNER(
	ID VARCHAR(300),
	NAME VARCHAR(300),
	PHONE VARCHAR(300),
	ADDR VARCHAR(1000),
	CONSTRAINT OWNER_PK PRIMARY KEY(ID)
);
DROP TABLE CAR;
CREATE TABLE CAR(
	CARNUM VARCHAR(300),
	BRAND VARCHAR(300),
	COLOR VARCHAR(300),
	PRICE INT,
	ID VARCHAR(300),
	CONSTRAINT CAR_PK PRIMARY KEY(CARNUM),
	CONSTRAINT CAR_OWNER_FK FOREIGN KEY(ID) REFERENCES OWNER(ID)
);











