--주석 : 해석하지 못하도록 하는 기법
--1. 소스코드에 설명글을 달 때
--2. 더 이상 사용하지 않는 소스코드를 해석하고 싶지 않을 때
/*EMPLOYEES테이블의 전체 내용 검색
SELECT * FROM EMPLOYEES;*/

--자동차 테이블 생성
CREATE TABLE CAR(
	ID NUMBER(3),
	BRAND VARCHAR2(20),
	COLOR VARCHAR2(10),
	PRICE NUMBER(10),
	--제약조건
	CONSTRAINT CAR_PK PRIMARY KEY(ID)
);
DROP TABLE CAR;
--제약조건 삭제
ALTER TABLE CAR DROP CONSTRAINT CAR_PK;

--제약조건 추가
ALTER TABLE CAR ADD
CONSTRAINT CAR_PK PRIMARY KEY(ID);

INSERT INTO CAR
--컬럼명
(ID, BRAND, COLOR, PRICE)
--추가할 값
VALUES(1, 'BENTELY', 'WHITE', 350000000);

SELECT * FROM CAR;

--동물 테이블 생성(PK 제약 조건은 생성 후 ALTER명령어로 준다.)
--ID, 종류, 나이, 먹이
--행 한 개 추가하기
CREATE TABLE ANIMAL(
	ID NUMBER(2),
	"TYPE" VARCHAR2(20),
	AGE NUMBER(3),
	FEED VARCHAR2(20)
);

DROP TABLE ANIMAL;

ALTER TABLE ANIMAL ADD CONSTRAINT ANI_PK PRIMARY KEY(ID);

INSERT INTO ANIMAL
(ID, "TYPE", AGE, FEED)
VALUES(1, '강아지', 3, '사료');

SELECT * FROM ANIMAL;

--제약 조건 DEFAULT와 CHECK
CREATE TABLE STUDENT(
	ID NUMBER(8),
	NAME VARCHAR2(15),
	MAJOR VARCHAR2(20),
	--조건식 : 참 또는 거짓이 나오는 식
	--컬럼명 IN(A,B) : A OR B
	--CHECK(조건식)
	GENDER CHAR(1) DEFAULT 'W' NOT NULL CONSTRAINT BAN_CHAR CHECK(GENDER IN ('M', 'W')),
	--DATE타입의 값을 비교할 때에는 -로 구분점을 준다.
	BIRTH DATE CONSTRAINT BAN_DATE CHECK(BIRTH >= TO_DATE('1980-01-01', 'YYYY-MM-DD')),
	CONSTRAINT STD_PK PRIMARY KEY(ID)
);

INSERT INTO STUDENT
(ID, NAME, MAJOR, BIRTH)
VALUES(1, '한동석', '건축학과', TO_DATE('1980-01-09','YYYY-MM-DD'));

SELECT * FROM STUDENT;
-------------------------------------------
INSERT INTO CAR
(ID, BRAND, COLOR, PRICE)
VALUES(2, 'AUDI', 'BLACK', 80000000);

INSERT INTO CAR
(ID, BRAND, COLOR, PRICE)
VALUES(3, 'BMW', 'BLUE', 70000000);

SELECT * FROM CAR;
TRUNCATE TABLE CAR;
--CAR2로 테이블명 변경
ALTER TABLE CAR RENAME TO CAR2;

SELECT * FROM CAR2;

--DATE타입 REALEASE 컬럼 추가
ALTER TABLE CAR2 ADD(REALEASE DATE);

SELECT * FROM CAR2;

INSERT INTO CAR2
(ID, BRAND, COLOR, PRICE, REALEASE)
VALUES(1, 'BENZ', 'BLACK', 180000000, TO_DATE('2019-12-20', 'YYYY-MM-DD'));

SELECT * FROM CAR2;

INSERT INTO CAR2
(ID, BRAND, COLOR, PRICE, REALEASE)
VALUES(2, 'MATIZ', 'GOLD', 500000, SYSDATE);

SELECT * FROM CAR2;

ALTER TABLE CAR2 RENAME COLUMN BRAND TO NAME;

SELECT * FROM CAR2;

ALTER TABLE CAR2 DROP COLUMN COLOR;

SELECT * FROM CAR2;

TRUNCATE TABLE CAR2;

ALTER TABLE CAR2 RENAME TO CAR;

SELECT * FROM CAR;

DROP TABLE CAR;

/*
 * FLOWER 테이블 생성하기
 * 컬럼명 : NAME, AGE, COLOR
 * FLOWER에서 FLOWER2로 테이블명 변경
 * FLOWER2에서 PRICE 컬럼 추가
 * INSERT로 값 넣기(2행)
 * FLOWER2테이블 값들 삭제하기(TRUNCATE)
 * FLOWER2테이블 전체 삭제하기(DROP)
 * 
 */
CREATE TABLE FLOWER(
	NAME VARCHAR2(20),
	AGE NUMBER(4),
	COLOR VARCHAR2(10)
);

ALTER TABLE FLOWER RENAME TO FLOWER2;
ALTER TABLE FLOWER2 ADD(PRICE NUMBER(6));

SELECT * FROM FLOWER2;

INSERT INTO FLOWER2
(NAME, AGE, COLOR, PRICE)
VALUES('장미', 1, 'RED', 3000);

INSERT INTO FLOWER2
(NAME, AGE, COLOR, PRICE)
VALUES('해바라기', 3, 'YELLOW', 5000);

TRUNCATE TABLE FLOWER2;

SELECT * FROM FLOWER2;

DROP TABLE FLOWER2;

























