CREATE TABLE STUDENT(
	ID NUMBER(3),
	NAME VARCHAR2(20),
	MAJOR VARCHAR2(20),
	--조건식 : TRUE , FALSE 두가지의 결과로 나오는 식
	--컬럼명 IN (값1,값2,...) : 값1 or 값2 or ...
	GENDER CHAR(1) CONSTRAINT BAN_CHAR CHECK(GENDER IN ('M','W')),
	BIRTH DATE CONSTRAINT BAN_DATE CHECK(BIRTH >= TO_DATE('1980-01-01','YYYY-MM-DD')),
	CONSTRAINT STD_PK PRIMARY KEY(ID)
);

INSERT INTO HR.STUDENT
(ID, NAME, MAJOR, GENDER, BIRTH)
VALUES(1, '정다솔', '기계공학', 'M', TO_DATE('2000/02/17','YYYY/MM/DD'));

INSERT INTO HR.STUDENT
(ID, NAME, MAJOR, GENDER, BIRTH)
VALUES(3, '이용현', '화학공학', 'M', TO_DATE('1970-07-25','YYYY-MM-DD'));--'TO_DATE 형식' 검색하기!

--영화정보
--	배우
--	장르
--	제목
--	감독
--	개봉날짜
--	19
CREATE TABLE MOVIE(
	ACTOR VARCHAR2(500),
	GENRE VARCHAR2(20),
	TITLE VARCHAR2(100),
	DIRECTOR VARCHAR2(20),
	MOVIEDATE DATE CONSTRAINT M_DATE CHECK(MOVIEDATE >= TO_DATE('1900-01-01','YYYY-MM-DD')),
	AGE CHAR(2) CONSTRAINT M_AGE CHECK(AGE IN ('AA','19'))
);
--반(반대)정규화
-- TO_DATE() 함수는 통채로가 '시간데이터'다
INSERT INTO MOVIE
VALUES('황정민,박정민,이정재,최희서','범죄,액션','다악구','홍원찬',
TO_DATE('2020/08/05','YYYY/MM/DD'),'AA');

-- FOREIGN KEY 설정하는 방법

CREATE TABLE TEST1(
	A VARCHAR2(20) PRIMARY KEY,
	B VARCHAR2(20),
	C VARCHAR2(20),
	D VARCHAR2(20)
);

CREATE TABLE TEST2(
	E VARCHAR2(20) PRIMARY KEY,
	F VARCHAR2(20),
	A VARCHAR2(20),
	CONSTRAINT TEST2_FK FOREIGN KEY(A)
		REFERENCES TEST1(A)
);
INSERT INTO TEST1 VALUES('a','b','c','d');
INSERT INTO TEST2 VALUES('e','f','a');

CREATE TABLE TEST3(
	G VARCHAR2(20) NOT NULL,
	H VARCHAR2(20) UNIQUE
);



